trigger_words = [
    "anal",
    "anus",
    "arse",
    "ass",
    "assassin",
    "assassinate",
    "assassination",
    "assault",
    "assbagger",
    "assblaster",
    "assclown",
    "asscowboy",
    "asses",
    "assfuck",
    "assfucker",
    "asshat",
    "asshole",
    "assholes",
    "asshore",
    "assjockey",
    "asskiss",
    "asskisser",
    "assklown",           
    "asslick",
    "asslicker",
    "ballsack",
    "balls",
    "bastard",
    "bitch",
    "biatch",
    "bloody",
    "blowjob",
    "blow job",
    "bollock",
    "bollok",
    "boner",
    "boob",
    "bugger",
    "bum",
    "butt",
    "buttplug",
    "clitoris",
    "cock",
    "coon",
    "crap",
    "cunt",
    "damn",
    "dick",
    "dildo",
    "dyke",
    "fag",
    "feck",
    "fellate",
    "fellatio",
    "felching",
    "fuck",
    "f u c k",
    "fudgepacker",
    "fudge packer",
    "flange",
    "Goddamn",
    "homo",
    "jerk",
    "jizz",
    "knobend",
    "knob end",
    "labia",
    "muff",
    "prick",
    "pube",
    "pussy",
    "puss",
    "pussie",
    "pussies",
    "pussy",
    "pussycat",
    "pussyeater",
    "pussyfucker",
    "pussylicker",
    "pussylips",
    "pussylover",
    "pussypounder",
    "pusy",
    "queer",
    "scrotum",
    "sex",
    "suck",
    "sucker",
    "stripclub",
    "suckme",
    "sluts",
    "slutt",
    "slutting",
    "slutty",
    "slutwear",
    "slutwhore",
    "sexymoma",
    "sexy-slim",
    "sexed",
    "sexfarm",
    "sexhound",
    "sexhouse",
    "sexing",
    "sexkitten",
    "sexpot",
    "sexslave",
    "sextogo",
    "sextoy",
    "sextoys",
    "sexual",
    "sexually",
    "shit",
    "s hit",
    "sh1t",
    "slut",
    "smegma",
    "spunk",
    "tit",
    "tosser",
    "turd",
    "twat",
    "titfuck",
    "titfucker",
    "titfuckin",
    "titjob",
    "titlicker",
    "titlover",
    "vagina",
    "virgin",
    "virginbreaker",
    "vagina",
    "vaginal",
    "vatican",
    "vibr",
    "vibrater",
    "vibrator",
    "vietcong",
    "wank",
    "whore",
    "motherfucker",
    "madharchod",
    "chutiye",
    "chutiya",
    "gandu",
    "lode",
    "laude",
    "behen ke lode",
    "mothafuck",
    "mothafucka",
    "mothafuckaz",
    "mothafucked ",
    "mothafucker",
    "mothafuckin",
    "mothafucking ",
    "mothafuckings",
    "motherfuck",
    "motherfucked",
    "motherfucker",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherlovebone",
    "xxx",
    "oral",
    "randi",
    "randwa",
    "chut",
    "chutiya",
    "madherchod",
    "gaand",
    "gand",







    "aad",
    "aand",
    "bahenchod",
    "behenchod",
    "bhenchod",
    "bhenchodd",
    "b.c.",
    "bc",
    "bakchod",
    "bakchodd",
    "bakchodi",
    "bevda",
    "bewda",
    "bevdey",
    "bewday",
    "bhadua",
    "bhaduaa",
    "bhadva",
    "bhadvaa",
    "bhadwa",
    "bhadwaa",
    "bhosada",
    "bhosda",
    "bhosdaa",
    "b.s.d.k",
    "bhosdike",
    "bhonsdike",
    "bsdk",
    "bhosdiki",
    "bhosdiwala",
    "bhosdiwale",
    "bhosadchodal",
    "bhosadchod",
    "bhosadchodal",
    "babbe",
    "babbey",
    "bube",
    "bubey",
    "bur",
    "burr",
    "buurr",
    "buur",
    "charsi",
    "chooche",
    "choochi",
    "chuchi",
    "chhod",
    "chod",
    "chodd",
    "chudne",
    "chudney",
    "chudwa",
    "chudwaa",
    "chudwane",
    "chudwaane",
    "choot",
    "chut",
    "chute",
    "chutia",
    "chutiya",
    "chutiye",
    "chuttad",
    "chutad",
    "dalaal",
    "dalal",
    "dalle",
    "dalley",
    "gadhe",
    "gadhalund",
    "gaand",
    "gand",
    "gandu",
    "gandfat",
    "gandfut",
    "gandiya",
    "gandiye",
    "gote",
    "gotey",
    "gotte",
    "hag",
    "haggu",
    "hagne",
    "hagney",
    "harami",
    "haramjada",
    "haraamjaada",
    "haramzyada",
    "haraamzyaada",
    "haraamjaade",
    "haraamzaade",
    "haraamkhor",
    "haramkhor",
    "jhat",
    "jhaat",
    "jhaatu",
    "jhatu",
    "kutta",
    "kutte",
    "kuttey",
    "kutia",
    "kutiya",
    "kuttiya",
    "kutti",
    "landi",
    "landy",
    "laude",
    "laudey",
    "laura",
    "lora",
    "lauda",
    "ling",
    "loda",
    "lode",
    "lund",
    "launda",
    "lounde",
    "laundey",
    "laundi",
    "loundi",
    "laundiya",
    "loundiya",
    "lulli",
    "maar",
    "maro",
    "marunga",
    "madarchod",
    "madarchodd",
    "madarchood",
    "madarchoot",
    "madarchut",
    "m.c.",
    "mc",
    "mamme",
    "mammey",
    "moot",
    "mut",
    "mootne",
    "mutne",
    "mooth",
    "muth",
    "nunni",
    "nunnu",
    "nunna",
    "pesaab",
    "pesab",
    "peshaab",
    "peshab",
    "pilla",
    "pillay",
    "pille",
    "pilley",
    "pisaab",
    "pisab",
    "pkmkb",
    "porkistan",
    "raand",
    "rand",
    "randi",
    "randy",
    "suar",
    "tatte",
    "tatti",
    "tatty",
    "ullu",
    "teri maa ka bhosda",
    "teri maa ka bhosada",
    "teri maa ki chut",
    "teri maa ki chut me kutte ka lund",
    "teri maa ki gand",
    "teri maa ki gaand",
    "teri maa ki gaand me kutte ka lund",
    "teri maa ka bhosda",
    "teri maa ka bhosada",
    "teri maa ki chut",
    "teri maa ki chut me kutte ka lund",
    "teri maa ki gand",
    "teri maa ki gaand",
    "teri maa ka bhosda",
    "teri maa ka bhosada",
    "teri maa ki chut",
    "teri maa ki chut me kutte ka lund",
    "teri maa ki gand",
    "teri maa ki gaand",
    


]